services:
  api:
    build: .
    ports:
      - "3000:3000"
  webserver:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
